#good luck.
#rule downloader:
#this is a comment
#this is the rule list

https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/Function/UposRedirect.conf
#https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/UnlockVip/Kuwo.conf
https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/UnlockVip/Spotify.conf
https://raw.githubusercontent.com/rartv/EmbyPublic/test/quantumult-x/emby.conf
#https://raw.githubusercontent.com/DoingDog/qxrewrite/main/static/ForOwnUse.snippet
#https://raw.githubusercontent.com/DoingDog/qxrewrite/main/static/UnlockApp.conf
https://gist.githubusercontent.com/ddgksf/35a94372ae4271562f0139d8a80a94e5/raw/ForOwnUse.snippet
